[package]
name = "plotters-cairo"
version = "0.3.1"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Plotters Cairo backend"
homepage = "https://plotters-rs.github.io"
repository = "https://github.com/plotters-rs/plotters-cairo"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters-backend = "^0.3.0"

[dependencies.cairo-rs]
version = "0.15.11"
features = ["ps"]

[dev-dependencies]
plotters = {version = "^0.3.0", default_features = false}

